#!/bin/bash

# EnvManager — development environment setup.
#
# Idempotent: safe to re-run. See README.md for the manual equivalent.

set -euo pipefail

echo "🚀 Setting up EnvManager development environment"
echo ""

echo "📋 Checking prerequisites..."
command -v docker >/dev/null 2>&1 || { echo "❌ Docker is required. Aborting." >&2; exit 1; }
command -v uv     >/dev/null 2>&1 || { echo "❌ uv is required (https://docs.astral.sh/uv/). Aborting." >&2; exit 1; }
command -v npm    >/dev/null 2>&1 || { echo "❌ npm is required. Aborting." >&2; exit 1; }

# package-lock.json is generated by npm 11 (Node 24); npm 10 rejects it as out of
# sync with package.json, so `npm ci` fails. Warn rather than abort — the backend
# half of the setup is still useful.
NPM_MAJOR="$(npm --version | cut -d. -f1)"
if [ "$NPM_MAJOR" -lt 11 ]; then
  echo "⚠️  npm $NPM_MAJOR detected; this project's lockfile needs npm 11+ (Node 24+)."
fi
echo "✅ Prerequisites present"
echo ""

echo "🐳 Starting infrastructure containers (PostgreSQL, Redis, NATS)..."
docker-compose up -d postgres redis nats

echo "⏳ Waiting for PostgreSQL..."
until docker-compose exec -T postgres pg_isready -U envmgr >/dev/null 2>&1; do
  sleep 1
done
echo "✅ PostgreSQL ready"
echo ""

cd backend

# DEBUG=true is what permits the placeholder SECRET_KEY committed in the repo.
# Without a .env the app refuses to start — see app/core/config.py.
if [ ! -f .env ]; then
  echo "📝 Creating backend/.env from .env.example"
  cp .env.example .env
else
  echo "📝 backend/.env already present — leaving it alone"
fi

echo "🐍 Installing Python dependencies (uv sync)..."
uv sync

# `alembic upgrade head` only. Never `revision --autogenerate` here: init_db()
# calls create_all, so autogenerate sees tables as already existing and emits
# empty migrations — and running it during setup would leave a spurious revision
# in the developer's working tree. See CLAUDE.md.
echo "🗄️  Applying migrations..."
uv run alembic upgrade head

echo "👤 Seeding master admin..."
PYTHONPATH=. uv run python scripts/seed_master_admin.py

echo "🏢 Seeding demo tenant..."
PYTHONPATH=. uv run python - <<'PY'
import asyncio

from sqlalchemy import select

from app.core.security import get_password_hash
from app.db.base import AsyncSessionLocal
from app.db.models.user import Tenant, User


async def seed() -> None:
    async with AsyncSessionLocal() as session:
        tenant = (
            await session.execute(select(Tenant).where(Tenant.slug == "demo"))
        ).scalar_one_or_none()
        if tenant is None:
            tenant = Tenant(name="Demo Organization", slug="demo")
            session.add(tenant)
            await session.flush()
            print("✅ Created demo tenant")
        else:
            print("• Demo tenant already exists")

        existing = (
            await session.execute(
                select(User).where(User.tenant_id == tenant.id, User.username == "admin")
            )
        ).scalar_one_or_none()
        if existing is None:
            session.add(
                User(
                    tenant_id=tenant.id,
                    username="admin",
                    email="admin@demo.com",
                    password_hash=get_password_hash("admin123"),
                    role="Admin",
                    notification_preferences={"email": True, "slack": False, "teams": False},
                )
            )
            print("✅ Created demo admin (tenant demo / admin / admin123)")
        else:
            print("• Demo admin already exists")

        await session.commit()


asyncio.run(seed())
PY

cd ../frontend
echo ""
echo "⚛️  Installing frontend dependencies..."
if [ "$NPM_MAJOR" -ge 11 ]; then
  npm ci
else
  echo "⚠️  Skipping npm ci (needs npm 11+). Run it after upgrading Node."
fi

cd ..
echo ""
echo "🎉 Setup complete."
echo ""
echo "Next steps:"
echo "  1. Backend:   cd backend && uv run uvicorn app.main:app --reload"
echo "  2. Frontend:  cd frontend && npm run dev"
echo "  3. Open:      http://localhost:5173   (tenant demo / admin / admin123)"
echo ""
echo "API docs: http://localhost:8000/docs"
