"""add_environment_subsystem_version

Revision ID: 2436af1aef0c
Revises: 0d99256c6a56
Create Date: 2026-03-23 14:30:39.251305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2436af1aef0c'
down_revision: Union[str, None] = '0d99256c6a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
