"""add_master_admin_and_tenant_active

Revision ID: ff40b07fafab
Revises: 95ae48eac578
Create Date: 2026-03-23 08:25:40.334848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff40b07fafab'
down_revision: Union[str, None] = '95ae48eac578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user', sa.Column('is_master_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_master_admin')
    op.drop_column('tenant', 'is_active')
    # ### end Alembic commands ###
